title: <p align="center"> Marcos Rojas Pacheco </p>

logo: "/assets/img/FOTO.png"

description:  <p align="center">
  <a href="#"><img alt="Presentacion" src="https://img.shields.io/badge/PDF-_PRESENTACIÓN-RED"></a> |
  <a href="https://twitter.com/SunamyTW"><img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/sunamyTW?style=social"></a> |
  <a href="https://github.com/MarcusRojasPacheco"><img alt="GitHub followers" src="https://img.shields.io/github/followers/MarcusRojasPacheco?style=social"></a>
  </p>
  
  <p align="justify">
  POR PONER
  <br><br>
  Por Poner algo
  <br><br>
  </p>

theme: jekyll-theme-minimal
