title: Marcos Rojas Pacheco
favicon: "assets/img/FOTO.png"
logo: "/assets/img/FOTO.png"

description:
  <a href="#"><img alt="Presentacion" src="https://img.shields.io/badge/PDF-_PRESENTACIÓN-RED"></a>
  <a href="https://twitter.com/SunamyTW"><img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/sunamyTW?style=social"></a>
  <a href="https://github.com/MarcusRojasPacheco"><img alt="GitHub followers" src="https://img.shields.io/github/followers/MarcusRojasPacheco?style=social"></a>
  
  <p align="justify">
  POR PONER
  <br><br>
  Por Poner algo
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: G-FFBB3HN0KR # Google Analytics tracking ID